name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key.pem
        shell: bash

      - name: Set correct permissions for SSH key
        run: chmod 600 ~/.ssh/deploy_key.pem
        shell: bash

      - name: Deploy to Server
        run: |
          rsync -e "ssh -i ~/.ssh/deploy_key.pem -o StrictHostKeyChecking=no" \
            -av --exclude="..." . ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:${{ secrets.TARGET_DIR }}
        shell: bash
