name: Portfolio Deployment

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Deploy static site to EC2 instance
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > /tmp/private-key.pem
        chmod 600 /tmp/private-key.pem
        scp -r -i /tmp/private-key.pem . ubuntu@ec2-3-108-40-20.ap-south-1.compute.amazonaws.com:/var/www/html/
        rm /tmp/private-key.pem
