name: Portfolio Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy static site to EC2 instance
        run: |
          echo "$EC2_PRIVATE_KEY" > /tmp/private-key.pem
          chmod 600 /tmp/private-key.pem
          scp -r -i /tmp/private-key.pem -o StrictHostKeyChecking=no . ubuntu@ec2-3-108-40-20.ap-south-1.compute.amazonaws.com:/var/www/html/
          rm /tmp/private-key.pem
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Use sudo to copy
        run: |
          ssh -i /tmp/private-key.pem -o StrictHostKeyChecking=no ubuntu@ec2-3-108-40-20.ap-south-1.compute.amazonaws.com "sudo cp -r /var/www/html/*
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
